name: Release
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Delete all releases
        run: gh release list | sed 's/|/ /' | awk '{print $1, $8}' | while read -r line; do gh release delete -y "$line"; done
        env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Delete all tags
        run: |
          if [ $(git tag -l "$1") ]; then
              git tag --delete  $1
              git push --delete origin $1
          else
              echo tag named "$1" was not found
          fi
      
      - name: Get package name
        run:  echo "PACKAGE_NAME=${GITHUB_REPOSITORY##*\/}" >> $GITHUB_ENV
        
      - name: Delete all packages
        uses: actions/delete-package-versions@v3
        with: 
          package-name: ${{ env.PACKAGE_NAME }}
          min-versions-to-keep: 0
          
      - name: Get scope
        run:  echo "SCOPE=@${GITHUB_ACTOR}" >> $GITHUB_ENV
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: ${{ env.SCOPE }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: Publish package
        run:
          npm publish --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
